version: '3.9'

services:
  backend-dev:
    image: django-imgservice
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/appuser/app/imgservice
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - 8000:8000
    stdin_open: true

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5435:5432
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: